

package userinterface.VolunteerRole;


import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Enterprise.Enterprise;
import GlobalEcoSystem.Network.Network;
import GlobalEcoSystem.Org.AidOrganization;
import GlobalEcoSystem.Org.Org;
import GlobalEcoSystem.Org.OrganizationDirectory;
import GlobalEcoSystem.UserAccount.UserAccount;
import GlobalEcoSystem.WorkQueue.NurseWorkRequest;
import GlobalEcoSystem.WorkQueue.WorkRequest;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class VolunteerPortal extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
 
   private UserAccount userAccount;  
    private OrganizationDirectory od;
    private AidOrganization norg;
    EcoSystem business;
    
    /** Creates new form AdminWorkAreaJPanel */
    public VolunteerPortal(JPanel userProcessContainer,
                           UserAccount userAccount,
                           EcoSystem business, Org organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userAccount = userAccount;
        this.od = od;
         this.norg = (AidOrganization)organization;
         this.business =business;
         populateRequestTable();
      
        //valueLabel.setText();
    }
    
    public void populateRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel)workRequestJjTable.getModel();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy"); 
        model.setRowCount(0);
       // if(!dorg.getWorkQueue().getWorkRequestList().isEmpty())
        //{
        for(WorkRequest request : business.getWorkQueue().getWorkRequestList()){
              if(request instanceof NurseWorkRequest){ 
            Object[] row = new Object[5];
            //row[0] = request;
            row[0] = ((NurseWorkRequest) request).getPerson().getName();
            //row[1] = 
            row[1] = ((NurseWorkRequest) request).getPerson().getAddress();
            row[2] =((NurseWorkRequest) request).getDate();
            row[3] = ((NurseWorkRequest) request).getDays();
            row[4]  = ((NurseWorkRequest) request);
            //row[3] = request.
            model.addRow(row);
        }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nwa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJjTable = new javax.swing.JTable();
        acceptjButton = new javax.swing.JButton();
        processjButton = new javax.swing.JButton();
        jLabel3j = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nwa.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        nwa.setForeground(new java.awt.Color(0, 102, 204));
        nwa.setText("Nurse Work Area");
        add(nwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 400, -1));

        workRequestJjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "person name", "Address", "Date", "No. of Days", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 670, 110));

        acceptjButton.setBackground(new java.awt.Color(0, 102, 204));
        acceptjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        acceptjButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptjButton.setText("Accept");
        acceptjButton.setBorderPainted(false);
        acceptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptjButtonActionPerformed(evt);
            }
        });
        add(acceptjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 140, -1));

        processjButton.setBackground(new java.awt.Color(0, 102, 204));
        processjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        processjButton.setForeground(new java.awt.Color(255, 255, 255));
        processjButton.setText("Completed");
        processjButton.setBorderPainted(false);
        processjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processjButtonActionPerformed(evt);
            }
        });
        add(processjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 160, -1));

        jLabel3j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nurse_wa-removebg-preview.png"))); // NOI18N
        jLabel3j.setText("jLabel3");
        add(jLabel3j, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 600, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1780, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void acceptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 3);
        NurseWorkRequest request = (NurseWorkRequest) workRequestJjTable.getValueAt(selectedRow, 4);
        if(request.getReceiver()!=null)
        {
            //JOptionPane.showMessageDialog(null, "Request has been processed earlier!", "warning", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        if(request.getNstatus().equalsIgnoreCase("Volunteer Accepted")){
            JOptionPane.showMessageDialog(null, "Already accepted");
        }
        request.setReceiver(userAccount);
        request.setNstatus("Volunteer Accepted");
        populateRequestTable();
    }//GEN-LAST:event_acceptjButtonActionPerformed

    private void processjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        NurseWorkRequest ntwr = (NurseWorkRequest)workRequestJjTable.getValueAt(selectedRow, 4);
        if(ntwr.getReceiver() == null)
        {
            JOptionPane.showMessageDialog(null, "Please accept the request first", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(ntwr.getNstatus().equalsIgnoreCase("Request Completed"))
        {
            JOptionPane.showMessageDialog(null, "Request has already been completed!", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(ntwr.getNstatus().equalsIgnoreCase("Volunteer Accepted"))
        {
            ntwr.setNstatus("Request Completed");
            populateRequestTable();
        }

    }//GEN-LAST:event_processjButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3j;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nwa;
    private javax.swing.JButton processjButton;
    private javax.swing.JTable workRequestJjTable;
    // End of variables declaration//GEN-END:variables
    
}
