/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoundationRole;


import GlobalEcoSystem.DeliveryMan.DeliveryManDirectory;
import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Person.Person;
import GlobalEcoSystem.Person.PersonDirectory;
import GlobalEcoSystem.Pharmacy.Pharmacy;
import GlobalEcoSystem.Pharmacy.PharmacyDirectory;
import GlobalEcoSystem.PharmacyMenu.PMenu;
import GlobalEcoSystem.PharmacyMenu.PMenuDirectory;
import GlobalEcoSystem.PharmacyOrder.POrder;
import GlobalEcoSystem.PharmacyOrder.POrderDirectory;

import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class FoodManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodManagementJPanel
     */
       private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount account;
    private PersonDirectory personDirectory;
    private PharmacyDirectory pharmacyDirectory;
   
    private DeliveryManDirectory deliveryManDirectory;
    private PMenuDirectory pmenuDirectory;
    private POrderDirectory porderDirectory;
    private static int count = 1;
    public FoodManagementJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem,
                                PersonDirectory personDirectory, PharmacyDirectory pharmacyDirectory,
                                DeliveryManDirectory deliveryManDirectory, PMenuDirectory pmenuDirectory, POrderDirectory porderDirectory) {
        initComponents();
        
           this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
        this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
        this.pmenuDirectory = ecoSystem.getpMenuDirectory();
        this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.porderDirectory = ecoSystem.getpOrderDirectory();
        //valueLabel.setText(account.getUsername());
        //populateRequestTable();
        populateRestaurantCombo();
        //valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }

    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestTable.getModel();
        model.setRowCount(0);
       //SimpleDateFormat strDate = new SimpleDateFormat("MM/dd/yyyy");
       System.out.println("ecoSystem" + this.ecoSystem);
        for (POrder order : this.ecoSystem.getpOrderDirectory().getOrderDirectory()){
            System.out.println("Order" + order.getOrderId());
            if(account.getEmployee().getName().equals(order.getPerson().getName())) {
                Object[] row = new Object[7];
                row[0] = order;
                row[1] = order.getMenu().getItemName();
                row[2] = order.getPharmacy().getPharmName();
                row[3] = order.getPerson().getName();
                row[4] = order.getOrderStatus();
                row[5] = order.getQuantity();
              //  row[7] = order.getTime().toString();
                model.addRow(row);
    }
        }
    }
    
      public void populateRestaurantCombo() {
        selectjjComboBox.removeAllItems();
        selectjjComboBox.addItem("  ");
        for(Pharmacy res : ecoSystem.getPharmacyDirectory().getPharmacyDirectory()) {
            System.out.println("res" + res);
            selectjjComboBox.addItem(res.getPharmName());
        }
    }
      
       public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jtable1j.getModel();
        dtm.setRowCount(0);
        String pharmName = selectjjComboBox.getSelectedItem().toString();
        Pharmacy pharmacy = ecoSystem.getPharmacyDirectory().getPharmacy(pharmName);
        for(PMenu pmenu : ecoSystem.getpMenuDirectory().getPmenuDirectory()){
            if(pharmacy.getPharmName().equals(pmenu.getPharmaName())) {
                Object [] row = new Object[2];
                row[0] = pmenu;
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharrr = new javax.swing.JLabel();
        selectjjComboBox = new javax.swing.JComboBox<>();
        MenujButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable1j = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        QuanjText = new javax.swing.JTextField();
        OrderjButton = new javax.swing.JButton();
        enterprisejLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 35, 39));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pharrr.setText("FoodManagementPortal");
        pharrr.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pharrr.setForeground(new java.awt.Color(255, 255, 255));
        add(pharrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        selectjjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Food Source" }));
        selectjjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectjjComboBoxActionPerformed(evt);
            }
        });
        add(selectjjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, -1));

        MenujButton.setText("Display Menu");
        MenujButton.setBackground(new java.awt.Color(0, 102, 204));
        MenujButton.setBorderPainted(false);
        MenujButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        MenujButton.setForeground(new java.awt.Color(255, 255, 255));
        MenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenujButtonActionPerformed(evt);
            }
        });
        add(MenujButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jtable1j.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "FoodItem"
            }
        ));
        jScrollPane2.setViewportView(jtable1j);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 320, 130));

        jLabel2.setText("Select Quantity");
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 110, -1));
        add(QuanjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 89, -1));

        OrderjButton.setText("Request Order");
        OrderjButton.setBackground(new java.awt.Color(0, 102, 204));
        OrderjButton.setBorderPainted(false);
        OrderjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OrderjButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderjButtonActionPerformed(evt);
            }
        });
        add(OrderjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 130, 40));

        enterprisejLabel2.setText("Order details:");
        enterprisejLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterprisejLabel2.setForeground(new java.awt.Color(255, 255, 255));
        add(enterprisejLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 127, 30));

        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "FoodName", "FoodPlace", "Customer", "Status", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 780, 90));

        BackButton.setText("<< BACK");
        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setBorderPainted(false);
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 102, 204));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        jLabel4.setText("Food Source");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void selectjjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectjjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectjjComboBoxActionPerformed

    private void MenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenujButtonActionPerformed
        // TODO add your handling code here:
         if(selectjjComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a restaurant");
            return;
        }
        populateTable();
      
    }//GEN-LAST:event_MenujButtonActionPerformed

    private void OrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1j.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(QuanjText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter quantity", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int quantity = Integer.parseInt(QuanjText.getText());
        String pharmName = selectjjComboBox.getSelectedItem().toString();
        Pharmacy pharmacy = ecoSystem.getPharmacyDirectory().getPharmacy(pharmName);
        Person person = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getName());
        PMenu menu = (PMenu) jtable1j.getValueAt(selectedRow, 0);
        String status = "Order Placed";
        
        POrder order = ecoSystem.getpOrderDirectory().newOrder();
        order.setPerson(person);
        int min = 1000;  
        int max = 5000; 
        int orderIdGen = (int)(Math.random()*(max-min+1)+min);
        order.setOrderId(String.valueOf(orderIdGen));
        order.setQuantity(quantity);
        order.setMenu(menu);
        order.setPharmacy(pharmacy);
        order.setOrderStatus(status);
        order.setAllot(false);
        
        JOptionPane.showMessageDialog(null,"You have placed an order");
        populateRequestTable();
    }//GEN-LAST:event_OrderjButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FoundationPortal a = (FoundationPortal) component;
        //a.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MenujButton;
    private javax.swing.JButton OrderjButton;
    private javax.swing.JTextField QuanjText;
    private javax.swing.JLabel enterprisejLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable1j;
    private javax.swing.JLabel pharrr;
    private javax.swing.JComboBox<String> selectjjComboBox;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
