/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoundationRole;

import GlobalEcoSystem.Doctor.DoctorDirectory;
import GlobalEcoSystem.Driver.DriverDirectory;
import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Enterprise.Enterprise;
import GlobalEcoSystem.Grocer.GrocerDirectory;
import GlobalEcoSystem.Helper.HelperDirectory;
import GlobalEcoSystem.Network.Network;
import GlobalEcoSystem.Nurse.NurseDirectory;
import GlobalEcoSystem.Org.Org;
import GlobalEcoSystem.Org.PopulationOrganization;
import GlobalEcoSystem.Person.PersonDirectory;
import GlobalEcoSystem.Pharmacy.PharmacyDirectory;

import GlobalEcoSystem.UserAccount.UserAccount;
import GlobalEcoSystem.WorkQueue.DoctorWorkRequest;
import GlobalEcoSystem.WorkQueue.DriverWorkRequest;
import GlobalEcoSystem.WorkQueue.HelperWorkRequest;
import GlobalEcoSystem.WorkQueue.NurseWorkRequest;

import java.awt.CardLayout;
import javax.swing.JPanel;


public class FoundationPortal extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private UserAccount userAccount;
    /**
     * Creates new form HealthCheckupProcessPortal
     */
    EcoSystem ecosystem;
    GrocerDirectory grocerDirectory;
    PharmacyDirectory pharmacyDirectory;
    DoctorDirectory doctorDirectory;
    HelperDirectory helperDirectory;
    NurseDirectory nurseDirectory;
    PersonDirectory personDirectory;
    DriverDirectory driverDirectory;
    DriverWorkRequest dreq;
    NurseWorkRequest nreq;
    HelperWorkRequest hreq;
    DoctorWorkRequest docreq;
    Enterprise enterprise;
    Network network;
    Org organization;
    //JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem,HelperWorkRequest hreq,Enterprise ent,Network network,PopulationOrganization organization
    public FoundationPortal(JPanel userProcessContainer, UserAccount account, Org organization, Enterprise enterprise, EcoSystem ecoSystem, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
      
        this.userAccount = account;
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecoSystem;
        this.enterprise = enterprise;
        this.network = network; 
        this.organization = organization;
       // populateRequestTable();
    }
    
 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NursingjButton = new javax.swing.JButton();
        helperjButton = new javax.swing.JButton();
        cabjButton = new javax.swing.JButton();
        HealthjButton = new javax.swing.JButton();
        medijButton = new javax.swing.JButton();
        GrocerjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 35, 39));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NursingjButton.setBackground(new java.awt.Color(0, 51, 204));
        NursingjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        NursingjButton.setForeground(new java.awt.Color(255, 255, 255));
        NursingjButton.setText("Request Volunteer");
        NursingjButton.setBorderPainted(false);
        NursingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NursingjButtonActionPerformed(evt);
            }
        });
        add(NursingjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 310, 80));

        helperjButton.setBackground(new java.awt.Color(0, 51, 204));
        helperjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        helperjButton.setForeground(new java.awt.Color(255, 255, 255));
        helperjButton.setText("Request Monetary Help");
        helperjButton.setBorderPainted(false);
        helperjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helperjButtonActionPerformed(evt);
            }
        });
        add(helperjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 310, 80));

        cabjButton.setBackground(new java.awt.Color(0, 51, 204));
        cabjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cabjButton.setForeground(new java.awt.Color(255, 255, 255));
        cabjButton.setText("Schedule Pickup");
        cabjButton.setBorderPainted(false);
        cabjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabjButtonActionPerformed(evt);
            }
        });
        add(cabjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 710, 310, 80));

        HealthjButton.setBackground(new java.awt.Color(0, 51, 204));
        HealthjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        HealthjButton.setForeground(new java.awt.Color(255, 255, 255));
        HealthjButton.setText("Schedule Health Checkup");
        HealthjButton.setBorderPainted(false);
        HealthjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthjButtonActionPerformed(evt);
            }
        });
        add(HealthjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 310, 80));

        medijButton.setBackground(new java.awt.Color(0, 51, 204));
        medijButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        medijButton.setForeground(new java.awt.Color(255, 255, 255));
        medijButton.setText("Request Food");
        medijButton.setBorderPainted(false);
        medijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medijButtonActionPerformed(evt);
            }
        });
        add(medijButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 310, 80));

        GrocerjButton.setBackground(new java.awt.Color(0, 51, 204));
        GrocerjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        GrocerjButton.setForeground(new java.awt.Color(255, 255, 255));
        GrocerjButton.setText("Order Supplies");
        GrocerjButton.setBorderPainted(false);
        GrocerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrocerjButtonActionPerformed(evt);
            }
        });
        add(GrocerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 310, 80));

        jLabel1.setBackground(new java.awt.Color(36, 35, 39));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Foundation Reception Portal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 530, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void NursingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NursingjButtonActionPerformed
        // TODO add your handling code here:
        
         VolunteeringJPanel n = new VolunteeringJPanel(userProcessContainer,userAccount, ecosystem,nreq,enterprise,network,(PopulationOrganization) organization);
        userProcessContainer.add("VolunteeringJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_NursingjButtonActionPerformed

    private void cabjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabjButtonActionPerformed
        // TODO add your handling code here:
        
        CabJPanel n = new CabJPanel(userProcessContainer,userAccount, ecosystem,dreq,enterprise,network,(PopulationOrganization) organization);
        userProcessContainer.add("CabJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_cabjButtonActionPerformed

    private void helperjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helperjButtonActionPerformed
        // TODO add your handling code here:
        
        NgoJPanel n = new NgoJPanel(userProcessContainer,userAccount, ecosystem,hreq,enterprise,network,(PopulationOrganization) organization);
        userProcessContainer.add("NgoJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_helperjButtonActionPerformed

    private void medijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medijButtonActionPerformed
        // TODO add your handling code here:
        
         FoodManagementJPanel n = new FoodManagementJPanel(userProcessContainer, userAccount, ecosystem,
            ecosystem.getPersonDirectory(), ecosystem.getPharmacyDirectory(), 
            ecosystem.getDeliverymanDirectory() , ecosystem.getpMenuDirectory() , ecosystem.getpOrderDirectory() );
        userProcessContainer.add("FoodManagementJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_medijButtonActionPerformed

    private void GrocerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrocerjButtonActionPerformed
        // TODO add your handling code here:
        
        SupplyManagementJPanel n = new SupplyManagementJPanel(userProcessContainer, userAccount, ecosystem,
            ecosystem.getPersonDirectory(), ecosystem.getGrocerDirectory(), 
            ecosystem.getDeliverymanDirectory() , ecosystem.getgMenuDirectory() , ecosystem.getgOrderDirectory() );
        userProcessContainer.add("SupplyManagementJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_GrocerjButtonActionPerformed

    private void HealthjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthjButtonActionPerformed
        // TODO add your handling code here:
        DocJPanel docPanel = new DocJPanel(userProcessContainer,userAccount, ecosystem,docreq,enterprise,network,(PopulationOrganization) organization);
userProcessContainer.add("DocJPanel",docPanel);
CardLayout layout=(CardLayout)userProcessContainer.getLayout();
layout.next(userProcessContainer);
        
    }//GEN-LAST:event_HealthjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GrocerjButton;
    private javax.swing.JButton HealthjButton;
    private javax.swing.JButton NursingjButton;
    private javax.swing.JButton cabjButton;
    private javax.swing.JButton helperjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medijButton;
    // End of variables declaration//GEN-END:variables
}
