/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoundationRole;


import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Enterprise.Enterprise;
import GlobalEcoSystem.Network.Network;
import GlobalEcoSystem.Nurse.Nurse;
import GlobalEcoSystem.Org.PopulationOrganization;
import GlobalEcoSystem.Person.Person;
import GlobalEcoSystem.UserAccount.UserAccount;

import GlobalEcoSystem.WorkQueue.NurseWorkRequest;
import GlobalEcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class VolunteeringJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteeringJPanel
     */
      private JPanel userProcessContainer;
private EcoSystem ecoSystem;
private UserAccount account;
private NurseWorkRequest nreq;
private Enterprise ent;
private PopulationOrganization organization;
private Network network;
    public VolunteeringJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, NurseWorkRequest nreq, Enterprise ent, Network network, PopulationOrganization organization) {
initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.nreq = nreq;
        this.organization = organization;
        this.ent = ent;
        this.network = network;
        populateSeatsCombo();
        populateRequestTable();
       
    }

     public void populateSeatsCombo() {
        jComboBox122.removeAllItems();
        //jComboBox1.addItem(" ");
        
        for(Nurse res : ecoSystem.getNurseDirectory().getNurseDirectory()) {
            System.out.println("res" + res);
            
            jComboBox122.addItem(String.valueOf(res.getGender()));
            
            //selectComboBox.addItem(Integer.parseInt(res.getSeats())); String.valueOf(i)
            //jComboBox1.addItem(String.valueOf(res.getSeats()));
        }
    }
     
       public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable122.getModel();
        model.setRowCount(0);
        //for (Gene g : ((LabTestWorkRequest) request).getPatient().getGeneHistory().getGeneHistory()) {
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
        if (request instanceof NurseWorkRequest) {
        //DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        // if(account.getEmployee().getName().equals(((DriverWorkRequest) dreq).getPerson().getName())) {
        Object[] row = new Object[4];
        row[0] = ((NurseWorkRequest) request).getDate();
        //row[1] = ((NurseWorkRequest) request).getPerson().getName();
        //System.out.println((int) ((NurseWorkRequest) request).getDays());
        //System.out.println( price);
        
        row[2] =(int) ((NurseWorkRequest) request).getDays();
        //order.getQuantity() * order.getMenu().getPrice()
        row[3] = ((NurseWorkRequest) request);
        model.addRow(row);
//}
}
        }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EDText2 = new javax.swing.JTextField();
        banu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox122 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable122 = new javax.swing.JTable();
        bookButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        datePicker111 = new com.github.lgooddatepicker.components.DatePicker();

        setBackground(new java.awt.Color(36, 35, 39));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EDText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDText2ActionPerformed(evt);
            }
        });
        add(EDText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 121, -1));

        banu.setText("Request Volunteer");
        banu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        banu.setForeground(new java.awt.Color(255, 255, 255));
        add(banu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel2.setText("Start Date");
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel3.setText("No. of Days");
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel4.setText("Select Gender");
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        add(jComboBox122, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 130, -1));

        jTable122.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start Date", "Customer Name", "Days", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable122);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 545, 132));

        bookButton.setText("Request volunteer");
        bookButton.setBackground(new java.awt.Color(0, 102, 204));
        bookButton.setBorderPainted(false);
        bookButton.setForeground(new java.awt.Color(255, 255, 255));
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 140, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        backButton.setText("<< BACK");
        backButton.setBackground(new java.awt.Color(247, 247, 247));
        backButton.setBorderPainted(false);
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 584, -1, -1));
        add(datePicker111, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void EDText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDText2ActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
         LocalDate dt = LocalDate.from(ZonedDateTime.now());
       if (datePicker111.getDate() == null || dt.compareTo(datePicker111.getDate()) > 0 )
         {
             JOptionPane.showMessageDialog(null,"Please pick valid date", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
         }
        
         if(EDText2.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null,"Please enter the number of days of service", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         
            int days = Integer.parseInt(EDText2.getText());
        Person person = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getName());
        
        System.out.println(account.getEmployee().getName());
        
        System.out.println(person);
        
        //String customer = ((DriverWorkRequest) dreq).getPerson().getName();
        //Person address = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getAddress());
        LocalDate date = datePicker111.getDate();
       // LocalTime time = dateTimePicker1.getTimePicker().getTime();
        String status = "Volunteer Requested";
        NurseWorkRequest nreq = new NurseWorkRequest();
        nreq.setDays(days);
        nreq.setPerson(person);
        nreq.setDate(date);
        nreq.setNstatus(status);
        
         account.getWorkQueue().getWorkRequestList().add(nreq);
        ecoSystem.getWorkQueue().getWorkRequestList().add(nreq);
        
         JOptionPane.showMessageDialog(null,"You have successfully requested a Volunteer. Please wait for the volunteer to accept");
        populateRequestTable();
         
    }//GEN-LAST:event_bookButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FoundationPortal a = (FoundationPortal) component;
        //a.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EDText2;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel banu;
    private javax.swing.JButton bookButton;
    private com.github.lgooddatepicker.components.DatePicker datePicker111;
    private javax.swing.JComboBox<String> jComboBox122;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable122;
    // End of variables declaration//GEN-END:variables
}
