/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Employee.Employee;
import GlobalEcoSystem.Person.Person;
import GlobalEcoSystem.Person.PersonDirectory;
import GlobalEcoSystem.Role.PersonRole;
import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class CreateUser extends javax.swing.JPanel {

    /**
     * Creates new form CreateUser
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PersonDirectory personDirectory;
    public CreateUser(JPanel userProcessContainer, EcoSystem ecoSystem, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        genderjText = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phonenumberjText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usernamjeText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agejText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        pwdjText = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(36, 35, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setBackground(new java.awt.Color(0, 102, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.setBorderPainted(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 180, 40));
        jPanel1.add(genderjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 240, 32));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 750, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("NAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 71, -1));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        jPanel1.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 240, 34));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("PASSWORD :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 110, 46));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("AGE :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));
        jPanel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 240, 34));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        phonenumberjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberjTextActionPerformed(evt);
            }
        });
        jPanel1.add(phonenumberjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 240, 34));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ADDRESS :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
        jPanel1.add(usernamjeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 240, 34));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("E-MAIL :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        agejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextActionPerformed(evt);
            }
        });
        jPanel1.add(agejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 240, 34));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("PHONE NUMBER :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, 34));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("USERNAME :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Create  User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 230, -1));
        jPanel1.add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 240, 34));
        jPanel1.add(pwdjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(namejText.getText().isEmpty() ||
        agejText.getText().isEmpty() || genderjText.getText().isEmpty() || addressText.getText().isEmpty() ||
        addressText.getText().isEmpty() || emailText.getText().isEmpty() || phonenumberjText.getText().isEmpty()
        || usernamjeText.getText().isEmpty() || pwdjText.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");//Fields cannot be left empty
        return;
        }

        String Name = namejText.getText();


        boolean flag ;

        flag = Name.matches("^[a-zA-Z]+$");

        if(flag == false) {
        JOptionPane.showMessageDialog(null, "name cannot have integer values"); //name cannot have integer values
        return;
        }

        String name = Name;

        String email = emailText.getText();

        flag = email.matches("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");

        if(!flag) {
        JOptionPane.showMessageDialog(null, "Email Address must be in format of X@Y.Z");//Email Address must be in format of X@Y.Z
        return;
        }

        for(Person person : ecoSystem.getPersonDirectory().getPersonDirectory()) {
        if(person.getEmail().equals(email)) {
        JOptionPane.showMessageDialog(null, "Email Address already exists");//Email Address already exist
        }
        }

        String phoneNumber = phonenumberjText.getText();

        if(phoneNumber.length() != 10) {
        JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");//PhoneNumber must be of 10 digits
        return;
        }
        flag = phoneNumber.matches("^[0-9]+$");
        if(!flag) {
        JOptionPane.showMessageDialog(null, "Phone Number must have digits only");//Phone Number must have digits only
        return;
        }
        for(Person person : personDirectory.getPersonDirectory()) {
        if(person.getMobile().equals(phoneNumber)) {
        JOptionPane.showMessageDialog(null, "Phone Number already exists");//Phone Number already exists
        }
        }

        int age = 0;

        try {

        age = Integer.parseInt(agejText.getText());

        } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Age must have integers only");
        return;
        }

        String address = addressText.getText();
        String userName = usernamjeText.getText();
        String password = pwdjText.getText();
        //String dob = dobText.getText();
        String phonenumber = phonenumberjText.getText();
        String gender = genderjText.getText();



        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
        if(account.getUsername().equals(userName)) {
        JOptionPane.showMessageDialog(null, "Username Already exists");
        return;
        }
        }
        System.out.println("Testing Ecosystem");
        System.out.println(ecoSystem.toString());
        ecoSystem.getPersonDirectory().addPerson(userName, gender, name, email, phonenumber, address, agejText.getText());
        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(name);
        UserAccount usserAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new PersonRole());

        JOptionPane.showMessageDialog(null, "User Profile Created");
        

       

        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatient mcjp = (ManagePatient) component;
        mcjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void agejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextActionPerformed

    private void phonenumberjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberjTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField agejText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField genderjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namejText;
    private javax.swing.JTextField phonenumberjText;
    private javax.swing.JPasswordField pwdjText;
    private javax.swing.JTextField usernamjeText;
    // End of variables declaration//GEN-END:variables
}
