/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.Doctor.Doctor;
import GlobalEcoSystem.Doctor.DoctorDirectory;
import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Employee.Employee;
import GlobalEcoSystem.Role.DoctorRole;
import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class CreateDoctor extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctor
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private DoctorDirectory doctorDirectory;
    public CreateDoctor(JPanel userProcessContainer,EcoSystem ecosystem,DoctorDirectory doctorDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.doctorDirectory = doctorDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1cd = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailjText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobilejText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        UILabel = new javax.swing.JLabel();
        UIjText = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        addjButton = new javax.swing.JButton();
        specialityjText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pwdjText = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1cd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1cd.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1cd.setText("Register Doctor");
        add(jLabel1cd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 80, -1));

        namejText.setBackground(new java.awt.Color(36, 35, 39));
        add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 180, 30));

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 80, -1));

        emailjText.setBackground(new java.awt.Color(36, 35, 39));
        emailjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextActionPerformed(evt);
            }
        });
        add(emailjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 180, 30));

        mobileLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 80, -1));

        mobilejText.setBackground(new java.awt.Color(36, 35, 39));
        add(mobilejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 180, 30));

        addLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 80, -1));

        addText.setBackground(new java.awt.Color(36, 35, 39));
        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 180, 30));

        UILabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UILabel.setText("UserID:");
        add(UILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 80, -1));

        UIjText.setBackground(new java.awt.Color(36, 35, 39));
        add(UIjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 180, 30));

        pwdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pwdLabel.setText("Password:");
        add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 80, -1));

        addjButton.setBackground(new java.awt.Color(0, 102, 204));
        addjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addjButton.setForeground(new java.awt.Color(255, 255, 255));
        addjButton.setText("Add Details");
        addjButton.setBorderPainted(false);
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 140, 40));

        specialityjText.setBackground(new java.awt.Color(36, 35, 39));
        specialityjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityjTextActionPerformed(evt);
            }
        });
        add(specialityjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 180, 30));

        specialityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        specialityLabel.setText("Speciality:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 80, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, -1, -1));

        pwdjText.setBackground(new java.awt.Color(36, 35, 39));
        pwdjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdjTextActionPerformed(evt);
            }
        });
        add(pwdjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
          String mobile = mobilejText.getText();
        String email = emailjText.getText();
        String userName = UIjText.getText();
        String password = pwdjText.getText();
        
        
         for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {
           
            if(doctor.getMobile().equals(mobile)) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists"); //Mobile Number already exists
            }
        }
         for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {
           
            if(doctor.getEmail().equals(email)) {
                JOptionPane.showMessageDialog(null, "Email already exists");//Email already exists
        }
         }
            for(UserAccount account : ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");//Username Already exists
                return;
            }
        }
        
        if (namejText.getText().isEmpty() || !namejText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");//Please enter valid name
        
        
        else if(!(mobilejText.getText().length()==10) || !mobilejText.getText().matches("^[0-9]+") || mobilejText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");//enter valid mobile number
        
      
       
        else if(emailjText.getText().isEmpty()|| !(emailjText.getText().trim().contains("@") && emailjText.getText().trim().contains(".")))
          JOptionPane.showMessageDialog(null, "Enter valid email address");//Enter valid email address
       
       
        else if (addText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter address");//Please enter address
        }
        
        else if (addText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter model");//Please enter model
        }
        
        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter userName");//Please enter userName
        
        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter password");//Please enter password
        
     
        else
           {
                   JOptionPane.showMessageDialog(null, "Doctor Profile Created");//Doctor Profile Created
                   
        ecosystem.getDoctorDirectory().newDoctor(userName,namejText.getText(),addText.getText(), email, mobile,specialityjText.getText());
        Employee employee = ecosystem.getEmployeeDirectory().createEmployee(namejText.getText());
        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DoctorRole());
           }
         

    }//GEN-LAST:event_addjButtonActionPerformed

    private void emailjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextActionPerformed

    private void specialityjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityjTextActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoctor mngDoc = (ManageDoctor) component;
        mngDoc.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void pwdjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdjTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel UILabel;
    private javax.swing.JTextField UIjText;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel jLabel1cd;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobilejText;
    private javax.swing.JTextField namejText;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JPasswordField pwdjText;
    private javax.swing.JLabel specialityLabel;
    private javax.swing.JTextField specialityjText;
    // End of variables declaration//GEN-END:variables
}
