/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;


import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Nurse.Nurse;
import GlobalEcoSystem.Nurse.NurseDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form ManageVolunteer
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private NurseDirectory nurseDirectory;
    public ManageVolunteer(JPanel userProcessContainer, EcoSystem ecosystem, NurseDirectory nurseDirectory) {
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.nurseDirectory = ecosystem.getNurseDirectory();
        //this.customerDirectory = customerDirectory;
        populateTable();
    }

     public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(Nurse nurse : ecosystem.getNurseDirectory().getNurseDirectory()){
            Object [] row = new Object[6];
            row[0] = nurse;
            row[1] = nurse.getName();
            row[2] = nurse.getGender();
            
            row[3] = nurse.getAddress();
            row[4] = nurse.getEmail();
            row[5] = nurse.getMobile();
           
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnjCreate = new javax.swing.JButton();
        btnajModify = new javax.swing.JButton();
        btnjDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 41));

        jPanel1.setBackground(new java.awt.Color(36, 35, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Volunteer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 360, 31));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "name", "gender", "address", "e-mail", "phone number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 175, 780, 120));

        btnjCreate.setBackground(new java.awt.Color(0, 102, 204));
        btnjCreate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnjCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnjCreate.setText("Create Volunteer");
        btnjCreate.setBorderPainted(false);
        btnjCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnjCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 351, 165, 30));

        btnajModify.setBackground(new java.awt.Color(0, 102, 204));
        btnajModify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnajModify.setForeground(new java.awt.Color(255, 255, 255));
        btnajModify.setText("Modify Volunteer");
        btnajModify.setBorderPainted(false);
        btnajModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnajModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 351, 165, 30));

        btnjDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnjDelete.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnjDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnjDelete.setText("Delete Volunteer");
        btnjDelete.setBorderPainted(false);
        btnjDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnjDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 351, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnjCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjCreateActionPerformed
         CreateVolunteer adddriv = new CreateVolunteer(userProcessContainer, ecosystem,nurseDirectory);
        userProcessContainer.add("CreateVolunteer",adddriv);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnjCreateActionPerformed

    private void btnajModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajModifyActionPerformed
            int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row to update");
            return;
        }
        Nurse nurse = (Nurse)jTable1.getValueAt(selectedRow,0);
        
        ModifyVolunteer modifyVolunteer = new ModifyVolunteer(userProcessContainer, ecosystem, nurseDirectory,nurse);
        userProcessContainer.add("ModifyVolunteer", modifyVolunteer);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnajModifyActionPerformed

    private void btnjDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjDeleteActionPerformed
            int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select a row to delete");
            return;
        }
        
         Nurse nurse = (Nurse)jTable1.getValueAt(selectedRow,0);
        nurseDirectory.removeNurse(nurse);
        populateTable();
    }//GEN-LAST:event_btnjDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnajModify;
    private javax.swing.JButton btnjCreate;
    private javax.swing.JButton btnjDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
