/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;


//import Business.Customer.Customer;
import GlobalEcoSystem.Helper.NGO;
import GlobalEcoSystem.Helper.HelperDirectory;
import GlobalEcoSystem.EcoSystem;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class manageHelper extends javax.swing.JPanel {

    /**
     * Creates new form manageHelper
     */
     private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private HelperDirectory helperDirectory;
    
    public manageHelper(JPanel userProcessContainer,EcoSystem ecosystem,HelperDirectory helperDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.helperDirectory = ecosystem.getHelperDirectory();
        //this.customerDirectory = customerDirectory;
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(NGO NGO : ecosystem.getHelperDirectory().getHelperDirectory()){
            Object [] row = new Object[6];
            row[0] = NGO;
            row[1] = NGO.getName();
            row[2] = NGO.getProfession();
            row[3] = NGO.getMobile();
            row[4] = NGO.getEmail();
            row[5] = NGO.getAddress();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addjButton = new javax.swing.JButton();
        updatejjButton = new javax.swing.JButton();
        deletejjButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 39));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage NGO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserId", "Name", "Profession", "Mobile", "Email", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 570, 110));

        addjButton.setBackground(new java.awt.Color(0, 102, 204));
        addjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addjButton.setForeground(new java.awt.Color(255, 255, 255));
        addjButton.setText("ADD");
        addjButton.setBorderPainted(false);
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 70, -1));

        updatejjButton.setBackground(new java.awt.Color(0, 102, 204));
        updatejjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatejjButton.setForeground(new java.awt.Color(255, 255, 255));
        updatejjButton.setText("UPDATE");
        updatejjButton.setBorderPainted(false);
        updatejjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejjButtonActionPerformed(evt);
            }
        });
        add(updatejjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        deletejjButton.setBackground(new java.awt.Color(153, 0, 0));
        deletejjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletejjButton.setForeground(new java.awt.Color(255, 255, 255));
        deletejjButton.setText("DELETE");
        deletejjButton.setBorderPainted(false);
        deletejjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejjButtonActionPerformed(evt);
            }
        });
        add(deletejjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
         addNGO addhelp = new addNGO(userProcessContainer, ecosystem, helperDirectory);
        userProcessContainer.add("CreateHelperJPanel",addhelp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addjButtonActionPerformed

    private void updatejjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejjButtonActionPerformed
        // TODO add your handling code here:
            int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row to update");
            return;
        }
        NGO help = (NGO)jTable1.getValueAt(selectedRow,0);
        
        updateNGO updateNGO = new updateNGO(userProcessContainer, ecosystem, helperDirectory,help);
        userProcessContainer.add("updtaeHelperJPanel", updateNGO);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updatejjButtonActionPerformed

    private void deletejjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select a row to delete");
            return;
        }
        
        NGO NGO = (NGO) jTable1.getValueAt(selectedRow, 0);
        helperDirectory.removeHelper(NGO);
        populateTable();
    }//GEN-LAST:event_deletejjButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deletejjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updatejjButton;
    // End of variables declaration//GEN-END:variables
}
