/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Helper.HelperDirectory;
import GlobalEcoSystem.Nurse.NurseDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ManageSupportServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupportServicesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    HelperDirectory helperDirectory;
    NurseDirectory nurseDirectory;
    public ManageSupportServicesJPanel(JPanel userProcessContainer,EcoSystem ecosystem,HelperDirectory helperDirectory,NurseDirectory nurseDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.helperDirectory = helperDirectory;
        this.nurseDirectory = nurseDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManagejHelper = new javax.swing.JButton();
        btnManagejNurse = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 35, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Support Services");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 479, 43));

        btnManagejHelper.setBackground(new java.awt.Color(0, 102, 204));
        btnManagejHelper.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnManagejHelper.setForeground(new java.awt.Color(255, 255, 255));
        btnManagejHelper.setText("Manage NGO");
        btnManagejHelper.setBorderPainted(false);
        btnManagejHelper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagejHelperActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagejHelper, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 244, 71));

        btnManagejNurse.setBackground(new java.awt.Color(0, 102, 204));
        btnManagejNurse.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnManagejNurse.setForeground(new java.awt.Color(255, 255, 255));
        btnManagejNurse.setText("Manage Volunteer");
        btnManagejNurse.setBorderPainted(false);
        btnManagejNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagejNurseActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagejNurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 244, 75));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagejHelperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagejHelperActionPerformed
        // TODO add your handling code here:
        manageHelper manageHelperPanel = new manageHelper(userProcessContainer,ecosystem,helperDirectory);
       userProcessContainer.add("manageHelper", manageHelperPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagejHelperActionPerformed

    private void btnManagejNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagejNurseActionPerformed
        // TODO add your handling code here:
        ManageVolunteer manageVolunteerPanel = new ManageVolunteer(userProcessContainer,ecosystem,nurseDirectory);
       userProcessContainer.add("ManageVolunteer", manageVolunteerPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagejNurseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManagejHelper;
    private javax.swing.JButton btnManagejNurse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
