/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Nurse.Nurse;
import GlobalEcoSystem.Nurse.NurseDirectory;
import GlobalEcoSystem.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ModifyVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form ModifyVolunteer
     */
    private JPanel userProcessContainer;
     private EcoSystem ecoSystem;
    private Nurse nurse;
    private UserAccountDirectory userAccountDirectory;
    private NurseDirectory nurseDirectory;
    public ModifyVolunteer(JPanel userProcessContainer, EcoSystem ecoSystem, NurseDirectory nurseDirectory, Nurse nurse) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.nurse = nurse;
        this.nurseDirectory = ecoSystem.getNurseDirectory();
        namejText.setText(nurse.getName());
        emailjText.setText(nurse.getEmail());
        addTjext.setText(nurse.getAddress());
        mobilejText.setText(nurse.getMobile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailjText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobilejText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addTjext = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Volunteer Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 460, 50));

        updatejButton.setBackground(new java.awt.Color(0, 102, 204));
        updatejButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        updatejButton.setForeground(new java.awt.Color(255, 255, 255));
        updatejButton.setText("Update");
        updatejButton.setBorderPainted(false);
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 110, 40));

        NameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, -1));
        add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 258, 180, 30));

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 80, -1));
        add(emailjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 308, 180, 30));

        mobileLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 80, -1));
        add(mobilejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 358, 180, 30));

        addLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 80, -1));
        add(addTjext, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 398, 180, 30));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobilejText.getText();
        String email = emailjText.getText();

        if (namejText.getText().isEmpty() || !namejText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        if(!(mobilejText.getText().length()==10) || !mobilejText.getText().matches("^[0-9]+") || mobilejText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        for(Nurse nurse : nurseDirectory.getNurseDirectory()) {

            if(nurse.getMobile().equals(mobile) && this.nurse != nurse) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }

        if(emailjText.getText().isEmpty()|| !(emailjText.getText().trim().contains("@") && emailjText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");
        for(Nurse nurse : nurseDirectory.getNurseDirectory()) {

            if(nurse.getEmail().equals(email) && this.nurse != nurse) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }

        if (addTjext.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Please enter address");

        nurse.setMobile(mobilejText.getText());
        nurse.setAddress(addTjext.getText());
        nurse.setName(namejText.getText());
        nurse.setEmail(emailjText.getText());

        JOptionPane.showMessageDialog(null, "Nurse Profile Updated");
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageVolunteer manageVolunteer = (ManageVolunteer) component;
        manageVolunteer.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addTjext;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobilejText;
    private javax.swing.JTextField namejText;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
