/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Person.Person;
import GlobalEcoSystem.Person.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ModifyPatient extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePatient
     */
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PersonDirectory personDirectory;
    private Person person;
    public ModifyPatient(JPanel userProcessContainer,EcoSystem ecoSystem,PersonDirectory personDirectory,Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
        this.person = person;
        namejText.setText(person.getName());
        emailjText.setText(person.getEmail());
        addressjText.setText(person.getAddress());
        phonenumberjText.setText(person.getMobile());
        //dobText.setText(person.getDob());
        agejText.setText(person.getAge());
        gendejrText.setText(person.getGender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2mp = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gendejrText = new javax.swing.JTextField();
        addressjText = new javax.swing.JTextField();
        emailjText = new javax.swing.JTextField();
        phonenumberjText = new javax.swing.JTextField();
        agejText = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        btnjBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2mp.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel2mp.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2mp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2mp.setText("Modify User");
        jPanel2.add(jLabel2mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 385, -1));

        namejText.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 300, 34));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 71, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("gender:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone Number:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, -1, 34));

        gendejrText.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.add(gendejrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 300, 32));

        addressjText.setBackground(new java.awt.Color(36, 35, 39));
        addressjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextActionPerformed(evt);
            }
        });
        jPanel2.add(addressjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 300, 34));

        emailjText.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.add(emailjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 300, 34));

        phonenumberjText.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.add(phonenumberjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 300, 34));

        agejText.setBackground(new java.awt.Color(36, 35, 39));
        jPanel2.add(agejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 300, 34));

        btnModify.setBackground(new java.awt.Color(0, 102, 204));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("Modify");
        btnModify.setBorderPainted(false);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel2.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 770, 150, 50));

        btnjBack.setBackground(new java.awt.Color(255, 255, 255));
        btnjBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnjBack.setForeground(new java.awt.Color(0, 0, 0));
        btnjBack.setText("<Back");
        btnjBack.setBorderPainted(false);
        btnjBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnjBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 850, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void addressjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        if(namejText.getText().isEmpty() ||
        agejText.getText().isEmpty() || gendejrText.getText().isEmpty() || addressjText.getText().isEmpty() ||
        addressjText.getText().isEmpty() || emailjText.getText().isEmpty() || phonenumberjText.getText().isEmpty()
        ) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
        return;
        }

        String Name = namejText.getText();


        boolean flag ;

        flag = Name.matches("^[a-zA-Z]+$");

        if(flag == false) {
        JOptionPane.showMessageDialog(null, "name cannot have integer values");
        return;
        }

        String name = Name;

        String email = emailjText.getText();

        flag = email.matches("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");

        if(!flag) {
        JOptionPane.showMessageDialog(null, "Email Address must be in format of X@Y.Z");
        return;
        }

        for(Person person : ecoSystem.getPersonDirectory().getPersonDirectory()) {
        if(person.getEmail().equals(email) && this.person != person) {
        JOptionPane.showMessageDialog(null, "Email Address already exists");
        }
        }

        String phoneNumber = phonenumberjText.getText();

        if(phoneNumber.length() != 10) {
        JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
        return;
        }
        flag = phoneNumber.matches("^[0-9]+$");
        if(!flag) {
        JOptionPane.showMessageDialog(null, "Phone Number must have digits only");
        return;
        }
        for(Person person : personDirectory.getPersonDirectory()) {
        if(person.getMobile().equals(phoneNumber) && this.person != person) {
        JOptionPane.showMessageDialog(null, "Phone Number already exists");
        }
        }

        int age = 0;

        try {

        age = Integer.parseInt(agejText.getText());

        } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Age must have integers only");
        return;
        }
        person.setName(name);
        person.setAge( Integer.toString (age));
        person.setGender(gendejrText.getText());
        person.setAddress(addressjText.getText()); 
        //person.setDob(dobText.getText());
        person.setMobile(phonenumberjText.getText());
        person.setEmail(email);
       JOptionPane.showMessageDialog(null, "Person profile update");
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnjBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatient mcjp = (ManagePatient) component;
        mcjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnjBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjText;
    private javax.swing.JTextField agejText;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnjBack;
    private javax.swing.JTextField emailjText;
    private javax.swing.JTextField gendejrText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2mp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namejText;
    private javax.swing.JTextField phonenumberjText;
    // End of variables declaration//GEN-END:variables
}
