/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Grocer.Grocer;
import GlobalEcoSystem.Grocer.GrocerDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class updateGrocer extends javax.swing.JPanel {

    /**
     * Creates new form updateGrocer
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private GrocerDirectory grocerDirectory;
    private Grocer grocer;
    public updateGrocer(JPanel userProcessContainer,EcoSystem ecosystem,GrocerDirectory grocerDirectory,Grocer grocer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.grocerDirectory = ecosystem.getGrocerDirectory();
        this.grocer = grocer;
        namejText.setText(grocer.getGrocerName());
        addressjText.setText(grocer.getAddress());
        mobilejText.setText(grocer.getPhoneNum());
        managerjText.setText(grocer.getManagerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        mobilejText = new javax.swing.JTextField();
        addressjText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        modifyjButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        managerjText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(36, 35, 41));
        setForeground(new java.awt.Color(0, 102, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        mobileLabel.setForeground(new java.awt.Color(255, 255, 255));
        mobileLabel.setText("Phone Number:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 80, -1));
        add(mobilejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 180, 30));

        addressjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextActionPerformed(evt);
            }
        });
        add(addressjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 180, 30));

        specialityLabel.setForeground(new java.awt.Color(255, 255, 255));
        specialityLabel.setText("Address:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, -1));

        NameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Supplier Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, -1));
        add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 180, 30));

        modifyjButton.setBackground(new java.awt.Color(0, 102, 204));
        modifyjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyjButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyjButton.setText("Modify");
        modifyjButton.setBorderPainted(false);
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });
        add(modifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 110, 40));

        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Manager:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 80, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        managerjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerjTextActionPerformed(evt);
            }
        });
        add(managerjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addressjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobilejText.getText();
        String address = addressjText.getText();
        String name = namejText.getText();
        if(namejText.getText().isEmpty() || mobile.isEmpty() ||
        managerjText.getText().isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
        return;
        }
        for(Grocer grocer : grocerDirectory.getGrocerDirectory()) {

            if(grocer.getPhoneNum().equals(mobile) && this.grocer != grocer) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }


        if (namejText.getText().isEmpty() || !namejText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        else if(!(mobilejText.getText().length()==10) || !mobilejText.getText().matches("^[0-9]+") || mobilejText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        else if (address.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter address");
        }


        else
        {
            JOptionPane.showMessageDialog(null, "Grocer profile modified");

            grocer.setAddress(address);
            grocer.setGrocerName(name);
            grocer.setManagerName(managerjText.getText());
            grocer.setPhoneNum(mobile);
           // UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new GrocerRole());
        }
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSupplyAdmin grocer = (ManageSupplyAdmin) component;
        grocer.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void managerjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerjTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_managerjTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField addressjText;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField managerjText;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobilejText;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField namejText;
    private javax.swing.JLabel specialityLabel;
    // End of variables declaration//GEN-END:variables
}
