/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.Driver.Driver;
import GlobalEcoSystem.Driver.DriverDirectory;
import GlobalEcoSystem.EcoSystem;

import GlobalEcoSystem.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class updateDriver extends javax.swing.JPanel {

    /**
     * Creates new form updateDriver
     */
       private JPanel userProcessContainer;
     private EcoSystem ecoSystem;
    private Driver driver;
    private UserAccountDirectory userAccountDirectory;
    private DriverDirectory driverDirectory;
    public updateDriver(JPanel userProcessContainer, EcoSystem ecoSystem, DriverDirectory driverDirectory, Driver driver) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.driver = driver;
        this.driverDirectory = ecoSystem.getDriverDirectory();
        namejText.setText(driver.getName());
        emailjText.setText(driver.getEmail());
        addjText.setText(driver.getAddress());
        mobilejText.setText(driver.getMobile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailjText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobilejText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addjText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Driver Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 420, 50));

        updatejButton.setBackground(new java.awt.Color(0, 102, 204));
        updatejButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatejButton.setForeground(new java.awt.Color(255, 255, 255));
        updatejButton.setText("Update");
        updatejButton.setBorderPainted(false);
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 130, 40));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, -1, -1));

        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 80, -1));

        namejText.setBackground(new java.awt.Color(36, 35, 39));
        add(namejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 230, 30));

        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, -1));

        emailjText.setBackground(new java.awt.Color(36, 35, 39));
        emailjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextActionPerformed(evt);
            }
        });
        add(emailjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 230, 30));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 80, -1));

        mobilejText.setBackground(new java.awt.Color(36, 35, 39));
        add(mobilejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 230, 30));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 80, -1));

        addjText.setBackground(new java.awt.Color(36, 35, 39));
        add(addjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobilejText.getText();
        String email = emailjText.getText();
  

        if (namejText.getText().isEmpty() || !namejText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        if(!(mobilejText.getText().length()==10) || !mobilejText.getText().matches("^[0-9]+") || mobilejText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        for(Driver driver : driverDirectory.getDriverDirectory()) {

            if(driver.getMobile().equals(mobile) && this.driver != driver) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }

        if(emailjText.getText().isEmpty()|| !(emailjText.getText().trim().contains("@") && emailjText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");
        for(Driver driver : driverDirectory.getDriverDirectory()) {

            if(driver.getEmail().equals(email) && this.driver != driver) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }

        if (addjText.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Please enter address");

       
        driver.setMobile(mobilejText.getText());
        driver.setAddress(addjText.getText());
        driver.setName(namejText.getText());
        driver.setEmail(emailjText.getText());
        
        
        JOptionPane.showMessageDialog(null, "Driver Profile Updated");
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        manageDriver driver = (manageDriver) component;
        driver.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void emailjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addjText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobilejText;
    private javax.swing.JTextField namejText;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
