/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import GlobalEcoSystem.Doctor.Doctor;
import GlobalEcoSystem.Doctor.DoctorDirectory;
import GlobalEcoSystem.EcoSystem;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class updateDoctor extends javax.swing.JPanel {

    /**
     * Creates new form updateDoctor
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private DoctorDirectory doctorDirectory;
    private Doctor doctor;
    public updateDoctor(JPanel userProcessContainer,EcoSystem ecosystem,DoctorDirectory doctorDirectory,Doctor doctor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.doctorDirectory = doctorDirectory;
        this.doctor = doctor;
        mobilejText.setText(doctor.getMobile());
        nameText.setText(doctor.getName());
        specialityjText.setText(doctor.getSpeciality());
        emailjText.setText(doctor.getEmail());
        addjText.setText(doctor.getAddress());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobilejText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addjText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        modifyjButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        specialityjText = new javax.swing.JTextField();
        emailjText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobilejText.setBackground(new java.awt.Color(36, 35, 39));
        add(mobilejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 220, 30));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 120, -1));

        addjText.setBackground(new java.awt.Color(36, 35, 39));
        addjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjTextActionPerformed(evt);
            }
        });
        add(addjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 220, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modify Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 120, -1));

        nameText.setBackground(new java.awt.Color(36, 35, 39));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 220, 30));

        modifyjButton.setBackground(new java.awt.Color(0, 51, 204));
        modifyjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        modifyjButton.setText("Modify");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });
        add(modifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 130, 40));

        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 120, -1));

        specialityjText.setBackground(new java.awt.Color(36, 35, 39));
        specialityjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityjTextActionPerformed(evt);
            }
        });
        add(specialityjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 220, 30));

        emailjText.setBackground(new java.awt.Color(36, 35, 39));
        emailjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextActionPerformed(evt);
            }
        });
        add(emailjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 220, 30));

        specialityLabel.setText("Speciality:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 120, -1));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 120, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addjTextActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobilejText.getText();
        String email = emailjText.getText();
        String speciality = specialityjText.getText();
        String address = addjText.getText();
        if(nameText.getText().isEmpty() || email.isEmpty() ||
        speciality.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
        return;
        }
        
        for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {

            if(doctor.getMobile().equals(mobile) && this.doctor != doctor) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }
        for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {

            if(doctor.getEmail().equals(email) && this.doctor != doctor) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }



        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        else if(!(mobilejText.getText().length()==10) || !mobilejText.getText().matches("^[0-9]+") || mobilejText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        else if(emailjText.getText().isEmpty()|| !(emailjText.getText().trim().contains("@") && emailjText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");

        else if (addjText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter address");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Doctor profile updated");

            doctor.setAddress(address);
            doctor.setEmail(email);
            doctor.setMobile(mobile);
            doctor.setName(nameText.getText());
            doctor.setSpeciality(speciality);
            
        }
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void specialityjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityjTextActionPerformed

    private void emailjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoctor mngDoc = (ManageDoctor) component;
        mngDoc.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addjText;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobilejText;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel specialityLabel;
    private javax.swing.JTextField specialityjText;
    // End of variables declaration//GEN-END:variables
}
