/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodManagerRole;

import GlobalEcoSystem.DeliveryMan.DeliveryManDirectory;
import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Enterprise.Enterprise;
import GlobalEcoSystem.Network.Network;
import GlobalEcoSystem.Org.Org;
import GlobalEcoSystem.Org.PharmacyOrganization;
import GlobalEcoSystem.Person.PersonDirectory;
import GlobalEcoSystem.Pharmacy.PharmacyDirectory;
import GlobalEcoSystem.PharmacyMenu.PMenuDirectory;
import GlobalEcoSystem.PharmacyOrder.POrderDirectory;
import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class FoodManagementAdminPortal extends javax.swing.JPanel {

    /**
     * Creates new form AdminAreaJPanel
     */
    JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private Network network;
    private Enterprise enterprise;
    private PersonDirectory personDirectory;
    private PharmacyDirectory pharmacyDirectory;
    private DeliveryManDirectory deliveryManDirectory;
    private PMenuDirectory pmenuDirectory;
    private POrderDirectory porderDirectory;
    private PharmacyOrganization pharmacyOrganization;
    public FoodManagementAdminPortal(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, Org organisation, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.pharmacyOrganization = (PharmacyOrganization)organisation;
        this.network = network;
        this.enterprise = enterprise;
        valueLabel.setText(account.getUsername());
        this.personDirectory = ecoSystem.getPersonDirectory();
       this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
       this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.pmenuDirectory = ecoSystem.getpMenuDirectory();
        this.porderDirectory = ecoSystem.getpOrderDirectory();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1wpa = new javax.swing.JLabel();
        storejButton = new javax.swing.JButton();
        manageMenujButton = new javax.swing.JButton();
        manageOrderjButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1wpa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1wpa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1wpa.setText("Food Management Portal");
        add(jLabel1wpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 590, -1));

        storejButton.setBackground(new java.awt.Color(0, 102, 204));
        storejButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        storejButton.setForeground(new java.awt.Color(255, 255, 255));
        storejButton.setText("Manage Store Info");
        storejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storejButtonActionPerformed(evt);
            }
        });
        add(storejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 280, 45));

        manageMenujButton.setBackground(new java.awt.Color(0, 102, 204));
        manageMenujButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        manageMenujButton.setForeground(new java.awt.Color(255, 255, 255));
        manageMenujButton.setText("Manage menu");
        manageMenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenujButtonActionPerformed(evt);
            }
        });
        add(manageMenujButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 280, 49));

        manageOrderjButton.setBackground(new java.awt.Color(0, 102, 204));
        manageOrderjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        manageOrderjButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrderjButton.setText("Manage Orders");
        manageOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderjButtonActionPerformed(evt);
            }
        });
        add(manageOrderjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 280, 44));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Store:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void storejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storejButtonActionPerformed
        // TODO add your handling code here:
        ManageHotelInfo mrijp = new ManageHotelInfo(userProcessContainer,account, ecoSystem, pharmacyDirectory);
        userProcessContainer.add("manageRestJPanel",mrijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_storejButtonActionPerformed

    private void manageMenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenujButtonActionPerformed
        ManageHotelMenu manageHotelMenu = new ManageHotelMenu(userProcessContainer,account, ecoSystem, pharmacyDirectory,pmenuDirectory);
        userProcessContainer.add("manageHotelMenu", manageHotelMenu);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenujButtonActionPerformed

    private void manageOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderjButtonActionPerformed

        ManageHotelOrder manageHotelOrder = new ManageHotelOrder(userProcessContainer,account, ecoSystem, pharmacyDirectory,pmenuDirectory, porderDirectory);
        userProcessContainer.add("ManageHotelOrder", manageHotelOrder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1wpa;
    private javax.swing.JButton manageMenujButton;
    private javax.swing.JButton manageOrderjButton;
    private javax.swing.JButton storejButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
