/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodManagerRole;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Pharmacy.PharmacyDirectory;
import GlobalEcoSystem.PharmacyMenu.PMenuDirectory;
import GlobalEcoSystem.PharmacyOrder.POrder;
import GlobalEcoSystem.PharmacyOrder.POrderDirectory;


import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageHotelOrder extends javax.swing.JPanel {

    /**
     * Creates new form ManageHotelOrder
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private PharmacyDirectory pharmacyDirectory;
    private PMenuDirectory pmenuDirectory;
    private POrderDirectory porderDirectory;
    public ManageHotelOrder(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, PharmacyDirectory grocerDirectory, PMenuDirectory pmenuDirectory, POrderDirectory porderDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.account = account;
        this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
        this.pmenuDirectory = ecoSystem.getpMenuDirectory();
        this.porderDirectory = ecoSystem.getpOrderDirectory();
        populateTable();
    }
 public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1tab.getModel();
        dtm.setRowCount(0);
        
        for(POrder order : ecoSystem.getpOrderDirectory().getOrderDirectory()) {
            System.out.println(" Rest  " + account.getEmployee().getName() + "  " + order.getPharmacy().getPharmName());
            if(account.getEmployee().getName().equals(order.getPharmacy().getPharmName())) {
                Object [] row = new Object[5];
                row[0] = order;
                row[1] = order.getMenu().getItemName();
                row[2] = order.getQuantity();
                row[3] = order.getOrderStatus();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1mo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1tab = new javax.swing.JTable();
        OAjButton = new javax.swing.JButton();
        OCjButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1mo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1mo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1mo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1mo.setText("Manage Orders");
        add(jLabel1mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jTable1tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Item", "Quantity", "Order Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1tab);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 242, 564, 110));

        OAjButton.setBackground(new java.awt.Color(0, 102, 204));
        OAjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OAjButton.setForeground(new java.awt.Color(255, 255, 255));
        OAjButton.setText("Order Accepted");
        OAjButton.setBorderPainted(false);
        OAjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OAjButtonActionPerformed(evt);
            }
        });
        add(OAjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 160, 30));

        OCjButton1.setBackground(new java.awt.Color(0, 102, 204));
        OCjButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OCjButton1.setForeground(new java.awt.Color(255, 255, 255));
        OCjButton1.setText("Order Completed");
        OCjButton1.setBorderPainted(false);
        OCjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCjButton1ActionPerformed(evt);
            }
        });
        add(OCjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 180, 30));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< Back");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void OAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OAjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1tab.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        POrder order = (POrder)jTable1tab.getValueAt(selectedRow, 0);
        if(order.getOrderStatus().equals("Order Placed")) {
            order.setOrderStatus("Order Accepted");
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Order is already accepted or Completed");
            return;
        }
       // order.setOrderStatus();
        populateTable();
    }//GEN-LAST:event_OAjButtonActionPerformed

    private void OCjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1tab.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        POrder order = (POrder)jTable1tab.getValueAt(selectedRow, 0);
        if(order.getOrderStatus().equals("Order Accepted")) {
            order.setOrderStatus("Order Ready for Pick up");
            order.setAllot(true);
        }
        
        else if(order.getOrderStatus().equals("Order Placed")) {
            JOptionPane.showMessageDialog(null, "Order is should be accepted first");
            return;
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Order is already ready for pick up");
            return;
        }
        
        populateTable();
    }//GEN-LAST:event_OCjButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OAjButton;
    private javax.swing.JButton OCjButton1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1mo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1tab;
    // End of variables declaration//GEN-END:variables
}
