/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CarrierRole;

import GlobalEcoSystem.DeliveryMan.DeliveryManDirectory;
import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.GroceryOrder.GOrder;
import GlobalEcoSystem.GroceryOrder.GOrderDirectory;
import GlobalEcoSystem.PharmacyOrder.POrder;
import GlobalEcoSystem.PharmacyOrder.POrderDirectory;

import GlobalEcoSystem.UserAccount.UserAccount;
import GlobalEcoSystem.WorkQueue.WorkRequest;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class logisticsPortal extends javax.swing.JPanel {

  private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
     private DeliveryManDirectory deliveryManDirectory;
    private GOrderDirectory gorderDirectory;
    private POrderDirectory porderDirectory;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public logisticsPortal(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        
       this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
         this.gorderDirectory = business.getgOrderDirectory();
         this.porderDirectory = business.getpOrderDirectory();
        this.deliveryManDirectory = business.getDeliverymanDirectory();
      
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestTable1.getModel();
        model.setRowCount(0);
         ArrayList<WorkRequest> allOrders = new ArrayList<WorkRequest>();
        for(POrder porder : business.getpOrderDirectory().getOrderDirectory()) {
        allOrders.add(porder);
        }
        for(GOrder gorder : business.getgOrderDirectory().getOrderDirectory()) {
        allOrders.add(gorder);
        }
        
        for(WorkRequest order: allOrders){
            Object[] row = new Object[5];
        //for(int i = 0; i < allOrders.size(); i++){
        if(order instanceof POrder){
            POrder porder = (POrder)order;
           if( porder.getOrderStatus() != null && (porder.getOrderStatus().equals("Order Ready for Pick up")
                   || porder.getOrderStatus().equals("Order Picked up") || porder.getOrderStatus().equals("Delivered"))){
        //POrder porder = (POrder)order;   
        row[0] = ((POrder) order);
        row[1] = ((POrder) order).getOrderStatus();
        row[2] = ((POrder) order).getPerson().getName();
        row[3] = ((POrder) order).getPerson().getAddress();
        row[4] = ((POrder) order).getPharmacy().getPharmName();
        model.addRow(row);
           }
        }
        else{
                GOrder gorder = (GOrder)order;
            if( gorder.getOrderStatus() != null && (gorder.getOrderStatus().equals("Order Ready for Pick up")
                   || gorder.getOrderStatus().equals("Order Picked up") || gorder.getOrderStatus().equals("Delivered"))){   
            row[0] = ((GOrder) order);
            row[1] = ((GOrder) order).getOrderStatus();
            row[2] = ((GOrder) order).getPerson().getName();
            row[3] = ((GOrder) order).getPerson().getAddress();
            row[4] = ((GOrder) order).getGrocer().getGrocerName();
            model.addRow(row);
        }
          
        }
        
        }
       // for(GOrder order : business.getgOrderDirectory().getOrderDirectory()) {}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestTable1 = new javax.swing.JTable();
        jLabel1Heading = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 35, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignButton.setBackground(new java.awt.Color(0, 102, 204));
        assignButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        assignButton.setForeground(new java.awt.Color(255, 255, 255));
        assignButton.setText("Assign to me");
        assignButton.setBorderPainted(false);
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        add(assignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        processButton.setBackground(new java.awt.Color(0, 102, 204));
        processButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        processButton.setForeground(new java.awt.Color(255, 255, 255));
        processButton.setText("Process");
        processButton.setBorderPainted(false);
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        add(processButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        refreshButton.setBackground(new java.awt.Color(0, 102, 204));
        refreshButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.setBorderPainted(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        workRequestTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Status", "Customer", "Customer Address", "Store"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 570, 120));

        jLabel1Heading.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1Heading.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Heading.setText("Logistics Portal");
        add(jLabel1Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed

        int selectedRow = workRequestTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a order to assign");
            return;
        }
        
        WorkRequest request = (WorkRequest)workRequestTable1.getValueAt(selectedRow, 0);
        if(request instanceof POrder){
            if(((POrder) request).getOrderStatus().equalsIgnoreCase("Order Picked up")){
            JOptionPane.showMessageDialog(null, "Order already picked up");
            return;
            }
            if(((POrder) request).getOrderStatus().equalsIgnoreCase("Delivered")){
            JOptionPane.showMessageDialog(null, "Cannot assign a delivered order");
            return;
            }            
        ((POrder) request).setOrderStatus("Order Picked up");
        }
        else{
            if(((GOrder) request).getOrderStatus().equalsIgnoreCase("Delivered")){
            JOptionPane.showMessageDialog(null, "Cannot assign a delivered order");
            return;
            }  
            if(((GOrder) request).getOrderStatus().equalsIgnoreCase("Order Picked up")){
            JOptionPane.showMessageDialog(null, "Order already picked up");
            return;
            }  
        ((GOrder) request).setOrderStatus("Order Picked up");
        }
        request.setReceiver(userAccount);
        //request.set
        populateTable();
//        Order order = (Order) workRequestJTable.getValueAt(selectedRow,0);
//        order.setDeliveryMan(userAccount.getEmployee().getName());
//        order.setOrderStatus("Order Picked up");
//        populateTable();
//        populateDeliveryManTable();
        
    }//GEN-LAST:event_assignButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        
        int selectedRow = workRequestTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a order to deliver");
            return;
        }
        WorkRequest request = (WorkRequest)workRequestTable1.getValueAt(selectedRow, 0);
        //if(request){        
        if(request instanceof POrder){
            if(((POrder) request).getOrderStatus().equalsIgnoreCase("Delivered")){
            JOptionPane.showMessageDialog(null, "Order already delivered");
            return;
            }
            if(((POrder) request).getOrderStatus().equalsIgnoreCase("Order Ready for Pick up")){
            JOptionPane.showMessageDialog(null, "Please assign the order first");
            return;
            }
        ((POrder) request).setOrderStatus("Delivered");
        }
        else{
            if(((GOrder) request).getOrderStatus().equalsIgnoreCase("Delivered")){
            JOptionPane.showMessageDialog(null, "Order already delivered");
            return;
            }
            if(((GOrder) request).getOrderStatus().equalsIgnoreCase("Order Ready for Pick up")){
            JOptionPane.showMessageDialog(null, "Please assign the order first");
            return;
            }
        ((GOrder) request).setOrderStatus("Delivered");
        }
        request.setReceiver(userAccount);
        //request.set
        populateTable();
      //  } 
    }//GEN-LAST:event_processButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JLabel jLabel1Heading;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable workRequestTable1;
    // End of variables declaration//GEN-END:variables
}
