/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplyAdminRole;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Grocer.GrocerDirectory;
import GlobalEcoSystem.GroceryMenu.GMenuDirectory;
import GlobalEcoSystem.GroceryOrder.GOrder;
import GlobalEcoSystem.GroceryOrder.GOrderDirectory;

import GlobalEcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHotelOrder
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private GrocerDirectory grocerDirectory;
    private GMenuDirectory gmenuDirectory;
    private GOrderDirectory gorderDirectory;
    public ManageOrderJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem ecoSystem, GrocerDirectory grocerDirectory, GMenuDirectory gmenuDirectory, GOrderDirectory gorderDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.account = account;
        this.grocerDirectory = ecoSystem.getGrocerDirectory();
        this.gmenuDirectory = ecoSystem.getgMenuDirectory();
        this.gorderDirectory = ecoSystem.getgOrderDirectory();
        populateTable();
    }
 public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jjTable1.getModel();
        dtm.setRowCount(0);
        
        for(GOrder order : ecoSystem.getgOrderDirectory().getOrderDirectory()) {
            System.out.println(" Rest  " + account.getEmployee().getName() + "  " + order.getGrocer().getGrocerName());
            if(account.getEmployee().getName().equals(order.getGrocer().getGrocerName())) {
                Object [] row = new Object[5];
                row[0] = order;
                row[1] = order.getMenu().getItemName();
                row[2] = order.getQuantity();
                row[3] = order.getQuantity() * order.getMenu().getPrice();
                row[4] = order.getOrderStatus();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageOrrders = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jjTable1 = new javax.swing.JTable();
        OAjButton = new javax.swing.JButton();
        OCjButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 35, 39));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageOrrders.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        ManageOrrders.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrrders.setText("Manage Orders");
        add(ManageOrrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Item", "Quantity", "Price", "Order Status"
            }
        ));
        jScrollPane1.setViewportView(jjTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 564, 180));

        OAjButton.setBackground(new java.awt.Color(0, 102, 204));
        OAjButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OAjButton.setForeground(new java.awt.Color(255, 255, 255));
        OAjButton.setText("Order Accepted");
        OAjButton.setBorderPainted(false);
        OAjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OAjButtonActionPerformed(evt);
            }
        });
        add(OAjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        OCjButton1.setBackground(new java.awt.Color(0, 102, 204));
        OCjButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OCjButton1.setForeground(new java.awt.Color(255, 255, 255));
        OCjButton1.setText("Order Completed");
        OCjButton1.setBorderPainted(false);
        OCjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCjButton1ActionPerformed(evt);
            }
        });
        add(OCjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        backjButton.setBackground(new java.awt.Color(255, 255, 255));
        backjButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backjButton.setForeground(new java.awt.Color(0, 0, 0));
        backjButton.setText("<< Back");
        backjButton.setBorderPainted(false);
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void OAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OAjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jjTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        GOrder order = (GOrder)jjTable1.getValueAt(selectedRow, 0);
        if(order.getOrderStatus().equals("Order Placed")) {
            order.setOrderStatus("Order Accepted");
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Order is already accepted or Completed");
            return;
        }
        
        populateTable();
    }//GEN-LAST:event_OAjButtonActionPerformed

    private void OCjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCjButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jjTable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        GOrder order = (GOrder)jjTable1.getValueAt(selectedRow, 0);
        if(order.getOrderStatus().equals("Order Accepted")) {
            order.setOrderStatus("Order Ready for Pick up");
            order.setAllot(true);
        }
        
        else if(order.getOrderStatus().equals("Order Placed")) {
            JOptionPane.showMessageDialog(null, "Order is should be accepted first");
            return;
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Order is already ready for pick up");
            return;
        }
        
        populateTable();
    }//GEN-LAST:event_OCjButton1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManageOrrders;
    private javax.swing.JButton OAjButton;
    private javax.swing.JButton OCjButton1;
    private javax.swing.JButton backjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jjTable1;
    // End of variables declaration//GEN-END:variables
}
