/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplyAdminRole;

import GlobalEcoSystem.EcoSystem;
import GlobalEcoSystem.Grocer.Grocer;
import GlobalEcoSystem.Grocer.GrocerDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ModifyStoreInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModifyHotelInfo
     */
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private GrocerDirectory grocerDirectory;
    private Grocer grocer;
    public ModifyStoreInfoJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, GrocerDirectory grocerDirectory, Grocer grocer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.grocer = grocer;
        this.grocerDirectory = ecoSystem.getGrocerDirectory();
       RestNamejText.setText(grocer.getGrocerName());
        RestAddjjText.setText(grocer.getAddress());
        PhonejText.setText(grocer.getPhoneNum());
        ManNamejText.setText(grocer.getManagerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ugd = new javax.swing.JLabel();
        restaNameLab = new javax.swing.JLabel();
        RestAddressjLab = new javax.swing.JLabel();
        RestPhonejLab = new javax.swing.JLabel();
        ManNamejLab = new javax.swing.JLabel();
        RestNamejText = new javax.swing.JTextField();
        RestAddjjText = new javax.swing.JTextField();
        PhonejText = new javax.swing.JTextField();
        ManNamejText = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(36, 35, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ugd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ugd.setForeground(new java.awt.Color(255, 255, 255));
        ugd.setText("Update Supplier Details");
        jPanel1.add(ugd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        restaNameLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        restaNameLab.setForeground(new java.awt.Color(255, 255, 255));
        restaNameLab.setText("Supplier  Name");
        jPanel1.add(restaNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        RestAddressjLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        RestAddressjLab.setForeground(new java.awt.Color(255, 255, 255));
        RestAddressjLab.setText("Address:");
        jPanel1.add(RestAddressjLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        RestPhonejLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        RestPhonejLab.setForeground(new java.awt.Color(255, 255, 255));
        RestPhonejLab.setText("Phone:");
        jPanel1.add(RestPhonejLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        ManNamejLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        ManNamejLab.setForeground(new java.awt.Color(255, 255, 255));
        ManNamejLab.setText(" Manager Name:");
        jPanel1.add(ManNamejLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        RestNamejText.setBackground(new java.awt.Color(36, 35, 39));
        RestNamejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestNamejTextActionPerformed(evt);
            }
        });
        jPanel1.add(RestNamejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 230, 30));

        RestAddjjText.setBackground(new java.awt.Color(36, 35, 39));
        RestAddjjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestAddjjTextActionPerformed(evt);
            }
        });
        jPanel1.add(RestAddjjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 230, 30));

        PhonejText.setBackground(new java.awt.Color(36, 35, 39));
        PhonejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonejTextActionPerformed(evt);
            }
        });
        jPanel1.add(PhonejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 230, 30));

        ManNamejText.setBackground(new java.awt.Color(36, 35, 39));
        ManNamejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManNamejTextActionPerformed(evt);
            }
        });
        jPanel1.add(ManNamejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 230, 30));

        updatejButton.setBackground(new java.awt.Color(0, 102, 204));
        updatejButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        updatejButton.setForeground(new java.awt.Color(255, 255, 255));
        updatejButton.setText("Update");
        updatejButton.setBorderPainted(false);
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 140, 40));

        backjButton1.setBackground(new java.awt.Color(255, 255, 255));
        backjButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(0, 0, 0));
        backjButton1.setText("<< Back");
        backjButton1.setBorderPainted(false);
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RestNamejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestNamejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestNamejTextActionPerformed

    private void RestAddjjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestAddjjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestAddjjTextActionPerformed

    private void PhonejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonejTextActionPerformed

    private void ManNamejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManNamejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManNamejTextActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        String RestName = RestNamejText.getText();
        String address = RestAddjjText.getText();
        String phone = PhonejText.getText();
        String ManName = ManNamejText.getText();
        if(RestName.isEmpty() || ManName.isEmpty() ||
            phone.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        boolean flag ;

        //String phoneNumber = phone;

        if(phone.length() != 10) {
            JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
            return;
        }
        flag = phone.matches("^[0-9]+$");
        if(!flag) {
            JOptionPane.showMessageDialog(null, "Phone Number must have digits only");
            return;
        }
        for(Grocer res : grocerDirectory.getGrocerDirectory()) {
            if(res.getPhoneNum().equals(phone) && this.grocer != res) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        //String address = txtAddress.getText();

        grocer.setGrocerName(RestName);
        grocer.setManagerName(ManName);
        grocer.setPhoneNum(phone);
        grocer.setAddress(address);

        JOptionPane.showMessageDialog(null, "Restaurant Updated");
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageStoreInfoJPanel u = (ManageStoreInfoJPanel) component;
        u.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManNamejLab;
    private javax.swing.JTextField ManNamejText;
    private javax.swing.JTextField PhonejText;
    private javax.swing.JTextField RestAddjjText;
    private javax.swing.JLabel RestAddressjLab;
    private javax.swing.JTextField RestNamejText;
    private javax.swing.JLabel RestPhonejLab;
    private javax.swing.JButton backjButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel restaNameLab;
    private javax.swing.JLabel ugd;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
